name: Rotate Daily Image

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Pick a new image without repeats
        run: |
          shopt -s nullglob
          image_dir="images"
          used_file=".used_images.txt"
          all_images=($image_dir/*.jpg)

          if [ ${#all_images[@]} -eq 0 ]; then
            echo "No images found!"
            exit 1
          fi

          # Ensure used file exists
          touch "$used_file"

          # Count used and remaining images
          remaining_images=()
          for img in "${all_images[@]}"; do
            if ! grep -Fxq "$img" "$used_file"; then
              remaining_images+=("$img")
            fi
          done

          # If all images used, reset
          if [ ${#remaining_images[@]} -eq 0 ]; then
            echo "All images used. Resetting list..."
            > "$used_file"
            remaining_images=("${all_images[@]}")
          fi

          # Pick a random unused image
          random_index=$((RANDOM % ${#remaining_images[@]}))
          selected_image="${remaining_images[$random_index]}"

          # Copy to daily.jpg
          cp "$selected_image" daily.jpg

          # Record usage
          echo "$selected_image" >> "$used_file"

      - name: Push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git add daily.jpg .used_images.txt
          git commit -m "Update daily image" || exit 0
          git push
